# Generated by Django 4.0.6 on 2023-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmainmodel',
            name='Unique_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
