# Generated by Django 4.0.6 on 2023-02-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_of_birth',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
