# Generated by Django 4.0.6 on 2023-02-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
    ]
